spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: clients_route
        uri: http://localhost:8100/clients
        predicates:
        - Path=/clients/**
      - id: vaccines_route
        uri: http://localhost:8200/vaccines
        predicates:
        - Path=/vaccines/**
      - id: branches_route
        uri: http://localhost:8300/branches
        predicates:
        - Path=/branches/**
      - id: reports_route
        uri: http://localhost:8300/reports
        predicates:
        - Path=/reports/**
      - id: openapi_route
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8080


#http://localhost:8080/actuator/gateway/routes